// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseHeader: typeof import('./components/layouts/BaseHeader.vue')['default']
    BaseSideInfobox: typeof import('./components/layouts/BaseSideInfobox.vue')['default']
    Card: typeof import('./components/containers/Card.vue')['default']
    CardContainer: typeof import('./components/containers/CardContainer.vue')['default']
    CardKeywordButton: typeof import('./components/containers/CardKeywordButton.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
  }
}

export {}
