// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AboutMePage: typeof import('./components/pages/about/AboutMePage.vue')['default']
    BaseHeader: typeof import('./components/layouts/BaseHeader.vue')['default']
    BaseSideInfobox: typeof import('./components/layouts/BaseSideInfobox.vue')['default']
    Card: typeof import('./components/containers/Card.vue')['default']
    CommonView: typeof import('./components/pages/common/CommonView.vue')['default']
    DocumentPage: typeof import('./components/pages/common/DocumentPage.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    EmojiBox: typeof import('./components/containers/EmojiBox.vue')['default']
    FlexContainer: typeof import('./components/containers/FlexContainer.vue')['default']
    GridContainer: typeof import('./components/containers/GridContainer.vue')['default']
    HomePage: typeof import('./components/pages/common/HomePage.vue')['default']
    PlaygroundPage: typeof import('./components/pages/playground/PlaygroundPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestCardPublish: typeof import('./components/test/TestCardPublish.vue')['default']
  }
}

export {}
